### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [Sh4rko/ColmarAcademy#5]
Grade: Exceeds Expectations

This is an exceptional project! You're doing many things well: your code is easy to read and follow due to its clear structure and thorough commenting; you have a great grasp of how to apply classes and ids, and when to use which; your CSS is both responsive and sophisticated; and your code is efficient as well! 

Another resource that might interest you is Coolors.co, which generates color palettes that can bring a new element of design to your projects. Check it out if you like! Again, great job here and congratulations!

**Comment by Sh4rko** [comment]
thank you
